### ISSUE TITLE
Create ChromeOS example

### ISSUE THREAD

**Issue by thegecko** [thegecko/web-bluetooth-dfu#13]
Create ChromeOS example

**Comment by beaufortfrancois** [comment]
What is specific about Chrome OS there? It should work the same as Android.

**Comment by thegecko** [comment]
I intend to create an example with the manifest, background page and all the other ChromeOS app shizzle.

**Comment by beaufortfrancois** [comment]
Oki ;)

**Comment by thegecko** [comment]
On reflection, how useful would this really be. I fail to think of a situation where a user would create a chrome app instead of just using a web page for Web Bluetooth now that it's supported natively in the browser :)

**Comment by beaufortfrancois** [comment]
I can't think of a situation either now.

**Comment by thegecko** [comment]
I'll close this, then. Feel free to re-open if a use case arises
