### ISSUE TITLE
Unable to select a device on Windows 10 Chrome (Canary)

### ISSUE THREAD

**Issue by louisn** [thegecko/web-bluetooth-dfu#30]
A bluetooth device cannot be selected when running on Windows 10 Chrome (Canary) with the chrome://flags/#enable-experimental-web-platform-features enabled.

secure-dfu.js line 417 is reporting 'Cannot read property requestDevice of undefined.

**Comment by thegecko** [comment]
That error sounds like `navigator.usb` is not available which suggests web-bluetooth hasn't been enabled.

**Comment by louisn** [comment]
It has, I am connecting and interacting with a device using another
application on the same computer. The DFU feature doesn't appear to work.

**Comment by louisn** [comment]
I haven't resolved any issue with this app.  However I was able to get the application I'm working to select a device.
