### ISSUE TITLE
Can I set a custom PACKET_SIZE to speed up the process?

### ISSUE THREAD

**Issue by zoexx** [thegecko/web-bluetooth-dfu#36]
I tried 200 with iphone, it works, but failed with android.
it returns `0x08: "The state of the DFU process does not allow this operation"`.
Is there a way to find out that's the best PACKET_SIZE ?

**Comment by thegecko** [comment]
@zoexx I think increasing the packet size makes it faster, but de-stabilises the protocol somehow. There's probably a race condition with reading/writing characteristics which is different depending on hardware and bluetooth stack. Does it work for you on android with the default packet size?

**Comment by thegecko** [comment]
Any update on this?
