### ISSUE TITLE
Uncaught (in promise) DOMException: GATT operation already in progress.

### ISSUE THREAD

**Issue by hugobfr** [thegecko/web-bluetooth-dfu#38]
Hello there !

I am using your tool for my personal use, it is great and easy to adjust to my needs.

I just want to open an issue for anyone who might stumble upon this unhandled exception as I have found a workaround.

This exception can appear randomly during a firmware update:
`Uncaught (in promise) DOMException: GATT operation already in progress.`
The update stops, and needs to be restarted in order to resume the transfer.

After some investigation, I found out this exception is raised by the characteristic write in the function `sendOperation`.

The workaround I found is the following:

```
private sendOperation(characteristic: BluetoothRemoteGATTCharacteristic, operation: Array<number>, buffer?: ArrayBuffer): Promise<DataView> {
             ...
            characteristic.writeValue(value)
            .catch(() =>  {
                this.log("DOMException: GATT operation already in progress.")
                return Promise.resolve()
                    .then(() => this.delayPromise(500))
                    .then(() => { characteristic.writeValue(value);});
            });
```

Now, everyting works fine and the update continues when the exception is catched.

![dfu-update](https://user-images.githubusercontent.com/17874426/78135132-ab020300-7421-11ea-8eb7-f0672b5d910c.png)

**Comment by thegecko** [comment]
Thanks! Can you open a PR to discuss?

**Comment by tkomde** [comment]
I appreciate your great job! As I encountered the same issue frequently, I make PR instead of @hugobfr.
