### ISSUE TITLE
nRF51 Support

### ISSUE THREAD

**Issue by septs** [thegecko/web-bluetooth-dfu#49]
see https://developer.nordicsemi.com/nRF5_SDK/nRF51_SDK_v4.x.x/doc/html/group__dfu__ble__service__spec.html

**Comment by thegecko** [comment]
This [supports nRf51 with softdevice S130](https://github.com/thegecko/web-bluetooth-dfu#device-configuration)

**Comment by septs** [comment]
![Screenshot_20200905-203417_nRF_Connect](https://user-images.githubusercontent.com/3842474/92305168-370eec80-efb7-11ea-9c36-6d7952294187.png)

the target device DFU use 00001530-1212-efde-1523-785feabcd123

**Comment by thegecko** [comment]
I assume the default has changed, overwrite it here: https://github.com/thegecko/web-bluetooth-dfu/blob/d050b89497ae297829a772788e0c052781f4b945/src/secure-dfu.ts#L458

**Comment by septs** [comment]
OK.

**Comment by septs** [comment]
```
ERROR in ./src/components/SensorConsole/dfu/index.ts
Module not found: Error: Can't resolve 'web-bluetooth-dfu' in '/Users/septs/Projects/mops-vida-pm-watchdog/src/components/SensorConsole/dfu'
 @ ./src/components/SensorConsole/dfu/index.ts 2:0-42 6:20-29 7:25-34
 @ ./src/components/SensorConsole/FirmwareVersion.tsx
 @ ./src/components/SensorConsole/index.tsx
 @ ./src/Entry.tsx
 @ ./src/index.ts
```

**Comment by septs** [comment]
https://github.com/thegecko/web-bluetooth-dfu/blob/5cdb47563df3d2188d0f1051b9954022f56dcbd6/package.json#L10-L12
this syntax on webpack may not be supported.

Reference: https://webpack.js.org/configuration/resolve/

**Comment by septs** [comment]
@thegecko

**Comment by thegecko** [comment]
This is an old repo and wasn't designed with webpack in mind. PRs welcome.

**Comment by septs** [comment]
@thegecko do i allow many changes? e.q:
upgrade all packages
migrate tslint to eslint
use prettier format code

and some api break change.

etc.

**Comment by thegecko** [comment]
Please keep separate PRs focussed on a single area

**Comment by septs** [comment]
Sorry, I decided to write a more modern
https://github.com/NiceLabs/nordic-dfu
