### ISSUE TITLE
TypeError: crc16 is not a function

### ISSUE THREAD

**Issue by mjdietzx** [thegecko/web-bluetooth-dfu#5]
Error occurs when running 'example_web.html.'

**Comment by mjdietzx** [comment]
@thegecko

**Comment by thegecko** [comment]
argh, I forgot to sync the gh-pages branch after the merge. can you try again?

**Comment by mjdietzx** [comment]
https://thegecko.github.io/web-bluetooth-dfu/  -  Still returning the same error. Same error when running locally.

**Comment by thegecko** [comment]
Yeah, got it. Try again?

**Comment by mjdietzx** [comment]
Yup, working now. Thanks
