### ISSUE TITLE
dist folder not present in npm package

### ISSUE THREAD

**Issue by DanTheMan827** [thegecko/web-bluetooth-dfu#74]
The `dist` folder is not present in the NPM package, so tools like Webpack fail to find the appropriate file.

**Comment by thegecko** [comment]
Just installed the latest version of this (v1.2.0) and can confirm the javascript files are present in the `lib` folder as referenced by the main index file:

```javascript
module.exports = require("./lib/");
```

**Comment by DanTheMan827** [comment]
The browser script references the one in dist though

**Comment by thegecko** [comment]
I see. Should now be resolved in web-bluetooth-dfu@1.2.1
