### ISSUE TITLE
Missing typescript types

### ISSUE THREAD

**Issue by DanTheMan827** [thegecko/web-bluetooth-dfu#75]
The typescript files are present in the src folder, but there are no .d.ts files within the published package.

**Comment by thegecko** [comment]
Just installed the latest version of this (v1.2.0) and can confirm the types are present in the `types` folder as referenced by the `package.json` file:

```json
"types": "./types/index.d.ts",
```

**Comment by DanTheMan827** [comment]
I apologize, I could've sworn that folder was missing on my install (and maybe it was for some reason)
