### ISSUE TITLE
Updating the SoftDevice and or Bootloader via DFU not working

### ISSUE THREAD

**Issue by mjdietzx** [thegecko/web-bluetooth-dfu#8]
I believe this is because of the way the hex files are converted to binaries. My guess is a lot of padding is added and this padding is actually sent for the update. Currently looking into this.

**Comment by mjdietzx** [comment]
currently in hex2bin() if there are any jumps in the hex file we will get an error.

**Comment by thegecko** [comment]
This was a basic implementation I pulled together to get this project off the ground, perhaps a more comprehensive conversion routine is required.

**Comment by mjdietzx** [comment]
Yeah, I thought so. I'm going to start working on making hex2bin() more comprehensive. there are some notes here: https://github.com/NordicSemiconductor/nRF-Master-Control-Panel/blob/master/init%20packet%20handling/How%20to%20generate%20the%20INIT%20file%20for%20DFU.pdf

I'll keep hex2bin() general. then based on the ImageType we will have to modify the binary.
Application: Nothing needs to be done (unless it writes to UICR this needs to be removed)
SoftDevice: Must remove the Master boot record from binary data as this isn't ever updated (0x0-0x1000)
Bootloader: This writes to UICR, this data just needs to be removed.
softDevice + bootloader: same steps from softdevice and bootloader above. merge the modifed softdevice binary with the modified bootloader binary and write that as one blob (softdevice + bootloader)

**Comment by thegecko** [comment]
Nice! I look forward to it

**Comment by mjdietzx** [comment]
#11 Implemented and merged in this PR
